# Generated by Django 5.2.14 on 2026-05-18 20:08

import apps.organization.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Archivé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('code', models.CharField(help_text='Ex : AG-VDN', max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'ordering': ['mutuelle__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Mutuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Archivé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('code', models.CharField(help_text='Ex : MUT-DKR', max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Mutuelle',
                'verbose_name_plural': 'Mutuelles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Archivé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('code', models.CharField(help_text='Ex : BUR-VDN-01', max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bureaux', to='organization.agence', verbose_name='Agence')),
            ],
            options={
                'verbose_name': 'Bureau',
                'verbose_name_plural': 'Bureaux',
                'ordering': ['agence__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Archivé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('code', models.CharField(help_text='Ex : DIR-COM', max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('directeur', models.ForeignKey(blank=True, help_text="L'employé qui dirige cette direction (doit avoir le rôle Directeur).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions_dirigees', to='employees.employee', verbose_name='Directeur en charge')),
                ('parent_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_directions', to='organization.direction', verbose_name='Direction parente')),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='agence',
            name='mutuelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agences', to='organization.mutuelle', verbose_name='Mutuelle'),
        ),
        migrations.CreateModel(
            name='IPBureauMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Archivé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('ip_pattern', models.CharField(help_text='Format CIDR (192.168.7.0/24) ou IP unique (192.168.7.42)', max_length=50, validators=[apps.organization.models._validate_ip_pattern], verbose_name='Plage IP')),
                ('description', models.CharField(blank=True, help_text='Optionnel : étage, bâtiment, type de réseau…', max_length=200, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_mappings', to='organization.bureau', verbose_name='Bureau')),
            ],
            options={
                'verbose_name': 'Plage IP de bureau',
                'verbose_name_plural': 'Plages IP de bureau',
                'ordering': ['bureau__code', 'ip_pattern'],
                'constraints': [models.UniqueConstraint(fields=('bureau', 'ip_pattern'), name='unique_bureau_ip_pattern')],
            },
        ),
    ]
