# Generated by Django 5.2.14 on 2026-05-19 08:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Archivé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('name', models.CharField(default='Planning ACEP', max_length=200, verbose_name='Nom')),
                ('tolerance_minutes', models.PositiveSmallIntegerField(default=5, help_text="Au-delà de cette tolérance, l'arrivée est marquée comme un retard.", verbose_name='Tolérance retard (minutes)')),
                ('max_break_duration', models.DurationField(default=datetime.timedelta(seconds=5400), help_text='Une pause plus longue déclenche une anomalie.', verbose_name='Durée maximale de pause')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Planning',
                'verbose_name_plural': 'Plannings',
            },
        ),
        migrations.CreateModel(
            name='WeeklySaturdaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Archivé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('week_start_date', models.DateField(db_index=True, unique=True, verbose_name='Lundi de la semaine')),
                ('saturday_date', models.DateField(verbose_name='Date du samedi')),
                ('status', models.CharField(choices=[('DRAFT', 'En préparation'), ('VALIDATED', 'Validé (semaine à venir)'), ('LOCKED', 'Verrouillé (semaine en cours)'), ('DONE', 'Réalisé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('employees', models.ManyToManyField(blank=True, related_name='saturday_schedules', to='employees.employee', verbose_name='Employés planifiés')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saturday_schedules_finalized', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Planning hebdomadaire du samedi',
                'verbose_name_plural': 'Plannings hebdomadaires du samedi',
                'ordering': ['-week_start_date'],
            },
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Archivé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='Jour')),
                ('mode', models.CharField(choices=[('NOT_WORKED', 'Non travaillé'), ('MANDATORY', 'Obligatoire'), ('OPTIONAL', 'Optionnel (planning hebdomadaire)')], default='NOT_WORKED', max_length=20, verbose_name='Mode')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Début pause')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Fin pause')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='planning.planning')),
            ],
            options={
                'verbose_name': 'Horaire journalier',
                'verbose_name_plural': 'Horaires journaliers',
                'ordering': ['planning', 'day_of_week'],
                'constraints': [models.UniqueConstraint(fields=('planning', 'day_of_week'), name='unique_planning_day')],
            },
        ),
    ]
