# Generated by Django 5.2.14 on 2026-05-18 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Archivé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('work_date', models.DateField(db_index=True, verbose_name='Date')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('arrival_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name="IP à l'arrivée")),
                ('break_start', models.DateTimeField(blank=True, null=True, verbose_name='Début pause')),
                ('break_start_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP au début de pause')),
                ('break_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin pause')),
                ('break_end_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP à la fin de pause')),
                ('departure_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('departure_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP au départ')),
                ('arrival_bureau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals', to='organization.bureau', verbose_name="Bureau de connexion à l'arrivée")),
                ('break_end_bureau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='break_ends', to='organization.bureau', verbose_name='Bureau à la fin de pause')),
                ('break_start_bureau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='break_starts', to='organization.bureau', verbose_name='Bureau au début de pause')),
                ('departure_bureau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='organization.bureau', verbose_name='Bureau au départ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='employees.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-work_date', 'employee__user__matricule'],
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Archivé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('anomaly_type', models.CharField(choices=[('LATE', 'Retard'), ('NO_DEPARTURE', 'Départ non pointé'), ('LONG_BREAK', 'Pause anormalement longue'), ('UNKNOWN_IP', 'IP non rattachée à un bureau'), ('INCOHERENCE_BUREAU', "Incohérence : bureau de connexion ≠ bureau d'affectation")], max_length=30, verbose_name='Type')),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, 'Info'), (2, 'Avertissement'), (3, 'Critique')], default=2, verbose_name='Sévérité')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Validée')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Validée le')),
                ('acknowledgement_note', models.TextField(blank=True, verbose_name='Note de validation')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies_acknowledged', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
                ('time_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='attendance.timeentry', verbose_name='Pointage')),
            ],
            options={
                'verbose_name': 'Anomalie',
                'verbose_name_plural': 'Anomalies',
                'ordering': ['-time_entry__work_date', '-severity'],
            },
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['work_date', 'employee'], name='attendance__work_da_131d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['employee', '-work_date'], name='attendance__employe_716b37_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.UniqueConstraint(fields=('employee', 'work_date'), name='unique_employee_workdate'),
        ),
        migrations.AddConstraint(
            model_name='anomaly',
            constraint=models.UniqueConstraint(fields=('time_entry', 'anomaly_type'), name='unique_anomaly_per_entry_type'),
        ),
    ]
