# Generated by Django 5.2.14 on 2026-05-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Archivé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('CONSULTANT', 'Consultant')], default='CDI', max_length=20, verbose_name='Type')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, help_text='Vide pour CDI', null=True, verbose_name='Date de fin')),
                ('weekly_hours', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='Heures hebdomadaires')),
                ('salary_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salaire brut mensuel (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Archivé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Photo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('hire_date', models.DateField(verbose_name="Date d'embauche")),
                ('position', models.CharField(help_text="Intitulé libre : Caissier, Chargé clientèle, Directeur d'agence, etc.", max_length=200, verbose_name='Poste / Fonction')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['user__matricule'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Archivé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('name', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('file', models.FileField(upload_to='employees/documents/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Document employé',
                'verbose_name_plural': 'Documents employés',
                'ordering': ['-created_at'],
            },
        ),
    ]
